

#import <UIKit/UIKit.h>
#define kCLIENTID @"CMXDTX41EITPPW1GDNKSK3FAB0L4PYFG0HHCBTZ0L3M30QOX"
#define kCLIENTSECRET @"ZSJMMWS5HVXQLY4WVIESVRYEF4BTBMAZF3KPEYTP1G1V2BQM"

@interface ViewController : UIViewController

@end
